version: '3'

services:
  politicalpurse.web:
    image: politicalpurse.web
    build:
      context: ./PoliticalPurse.Web
      dockerfile: Dockerfile
    env_file:
      - ./PoliticalPurse.Web/.env
    depends_on:
      - politicalpurse-db
  politicalpurse-db:
    image: postgres:9.6.2
    expose:
      - '5432'
    ports:
      - '5500:5432'
    environment:
      POSTGRES_PASSWORD: 'Password1'
    volumes:
      - politicalpurse-db-volume:/var/lib/postgresql/data

volumes:
  politicalpurse-db-volume:
    external: true